services:
  lint:
    container_name: lint
    build:
        context: .
        dockerfile: lint.dockerfile
    volumes:
      - .:/app
  deploy:
    container_name: app
    build:
        context: .
        dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    restart: unless-stopped
